name: Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
        pip install sphinx-rtd-theme sphinx-autobuild myst-parser
        
    - name: Build documentation
      run: |
        cd docs
        make html
        
    - name: Check documentation coverage
      run: |
        cd docs
        make coverage
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true
        
  linkcheck:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
        pip install sphinx-rtd-theme sphinx-autobuild myst-parser
        
    - name: Check links
      run: |
        cd docs
        make linkcheck
        
    - name: Upload linkcheck results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: linkcheck-results
        path: docs/_build/linkcheck/
